import type { Metadata } from "next";
import WebAudio from "../views/components/WebAudio";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/registry";
import NavBar from "../views/components/NavBar";
import { Montserrat } from "next/font/google";
import TopMargin from "../views/components/TopMargin";
import { AuthProvider } from "../views/components/AuthContext";
import Footer from "../views/components/Footer";
import { ShoppingCartProvider } from "@/views/components/ShoppingCartContext";
import { RegisterProvider } from "../views/components/RegisterContext";

const montserrat = Montserrat({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "UnderSounds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <ShoppingCartProvider>
        <RegisterProvider>
          <html lang="en">
            <body className={`${montserrat.className} antialiased`}>
              <NavBar />
              <TopMargin />
              <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
              {/* Separación del audio para reproducirlo en todas las páginas */}
              <Footer />
            </body>
          </html>
        </RegisterProvider>
      </ShoppingCartProvider>
    </AuthProvider>
  );
}
