import type { Metadata } from "next";
import WebAudio from "./components/WebAudio";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/registry";
import NavBar from "./components/NavBar";
import { Montserrat } from "next/font/google";
import TopMargin from "./components/TopMargin";
import { AuthProvider } from "./components/AuthContext";

const montserrat = Montserrat( { subsets: ['latin'], weight: "400"} );

export const metadata: Metadata = {
  title: "UnderSounds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={`${montserrat.className} antialiased`}>
          <NavBar />
          <TopMargin />
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
          {/* Separación del audio para reproducirlo en todas las páginas */}
        </body>
      </html>
    </AuthProvider>
  );
}
